"""Tests for the gates/ layout: the repo gates live, run and get linted from one place."""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Set

GATE_NAMES = ("deps_guard.py", "docs_guard.py", "release_guard.py", "tdd_guard.py")

# Top-level directories holding *.py we do not author: mirrors of features/, regenerated by
# tooling/sync_plugin_skills.py and the scaffolder. Linting a copy lints nothing new.
GENERATED_PY_ROOTS = frozenset({".ai-badger", ".claude", "skills"})


def _tracked_python_roots(root: Path) -> Set[str]:
    out = subprocess.run(["git", "ls-files", "*.py"], cwd=str(root), capture_output=True,
                         text=True, check=True).stdout
    roots = {line.split("/")[0] for line in out.splitlines() if "/" in line}
    return roots - GENERATED_PY_ROOTS


def test_every_gate_lives_in_the_gates_directory(root):
    """A gate outside gates/ is a gate the pylint target and CI lane can silently miss."""
    assert sorted(p.name for p in (root / "gates").glob("*_guard.py")) == sorted(GATE_NAMES)
    for elsewhere in ("engine", "tooling"):
        assert sorted(p.name for p in (root / elsewhere).glob("*_guard.py")) == []


def test_every_gate_runs_from_its_new_home(root):
    """Each gate resolves badger_lib after the move; an ImportError here is the whole risk."""
    for name in GATE_NAMES:
        proc = subprocess.run([sys.executable, str(root / "gates" / name), "--help"],
                              cwd=str(root), capture_output=True, text=True, check=False)
        combined = proc.stdout + proc.stderr
        assert proc.returncode == 0, f"{name}: exit {proc.returncode}\n{combined}"
        assert "Traceback" not in combined, f"{name}: {combined}"
        assert "ImportError" not in combined, f"{name}: {combined}"


def test_every_gate_is_a_pylint_target(root):
    """The lint target must name every directory holding Python we own."""
    config = json.loads((root / ".ai-badger" / "config.json").read_text(encoding="utf-8"))
    targets = set(config["commands"]["lint"].split())
    missing = sorted(d for d in _tracked_python_roots(root) if d not in targets)
    assert not missing, f"unlinted directories holding our *.py: {missing}"
