"""Tests for review-tests/scripts/rules_index.py against tests/fixtures/test_ruleset_min/.

Every test copies the fixture into tmp_path first — never runs the script against the real
fixture directory in place (the suite's own write-isolation guard forbids writing inside a real
checkout; see conftest._test_write). "Red" tests plant one defect, assert --check fails and
names it, then assert the unmodified copy is clean — the pairing IS the red-proof
(prove-the-check-fails): a check that has only ever passed is not a check.
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

import pytest

SCRIPT = "features/common/skills/review-tests/scripts/rules_index.py"
FIXTURE = "tests/fixtures/test_ruleset_min"


@pytest.fixture
def rules_index(load_script):
    return load_script(SCRIPT)


def _copy_fixture(root: Path, tmp_path: Path, name: str = "min") -> Path:
    dest = tmp_path / name
    shutil.copytree(root / FIXTURE, dest)
    return dest


def _run(rules_index, fixture_root: Path, *extra: str) -> int:
    return rules_index.main(["--root", str(fixture_root), *extra])


def _run_captured(capsys, rules_index, fixture_root: Path, *extra: str):
    rc = _run(rules_index, fixture_root, *extra)
    return rc, capsys.readouterr().out


# ---------------------------------------------------------------------------
# Baseline: the fixture as committed is clean, and generation is idempotent.
# ---------------------------------------------------------------------------

def test_check_passes_on_the_clean_fixture(rules_index, root, tmp_path, capsys):
    fixture = _copy_fixture(root, tmp_path)
    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 0
    assert "up to date" in out


def test_generation_is_idempotent(rules_index, root, tmp_path):
    fixture = _copy_fixture(root, tmp_path)
    rc1 = _run(rules_index, fixture)
    first = {
        p.relative_to(fixture): p.read_text(encoding="utf-8")
        for p in (fixture / "rules.json",
                  fixture / "references" / "walk-review.md",
                  fixture / "references" / "walk-design.md")
    }
    rc2 = _run(rules_index, fixture)
    second = {
        p.relative_to(fixture): p.read_text(encoding="utf-8")
        for p in (fixture / "rules.json",
                  fixture / "references" / "walk-review.md",
                  fixture / "references" / "walk-design.md")
    }
    assert rc1 == 0
    assert rc2 == 0
    assert first == second


def test_walks_open_with_the_generated_banner(rules_index, root, tmp_path):
    fixture = _copy_fixture(root, tmp_path)
    _run(rules_index, fixture)
    banner = ("<!-- generated by scripts/rules_index.py — do not edit; "
              "edit the rule's meta: line instead -->")
    for name in ("walk-review.md", "walk-design.md"):
        text = (fixture / "references" / name).read_text(encoding="utf-8")
        assert text.startswith(banner)


def test_rules_json_carries_no_prose(rules_index, root, tmp_path):
    """AC5: no value in rules.json exceeds 200 characters — the no-prose guard."""
    fixture = _copy_fixture(root, tmp_path)
    _run(rules_index, fixture)
    index = json.loads((fixture / "rules.json").read_text(encoding="utf-8"))
    for record in index:
        for key, value in record.items():
            text = json.dumps(value)
            assert len(text) <= 200, f"{record['id']}.{key} is {len(text)} chars: {text!r}"


def test_rules_json_excludes_design_review_check_bodies(rules_index, root, tmp_path):
    """rules.json is structural only — design/review/check prose never lands in it."""
    fixture = _copy_fixture(root, tmp_path)
    _run(rules_index, fixture)
    index = json.loads((fixture / "rules.json").read_text(encoding="utf-8"))
    for record in index:
        assert "design" not in record
        assert "review" not in record
        assert "check" not in record


def test_l2_rule_is_placed_at_its_parents_pass_in_the_review_walk(rules_index, root, tmp_path):
    fixture = _copy_fixture(root, tmp_path)
    _run(rules_index, fixture)
    text = (fixture / "references" / "walk-review.md").read_text(encoding="utf-8")
    pass1 = text.split("## Pass 1", 1)[1].split("## Pass", 1)[0]
    assert "T1-AAA-01" in pass1
    assert "T2-WID-01" in pass1


def test_design_walk_omits_review_only_phase_rules(rules_index, root, tmp_path):
    fixture = _copy_fixture(root, tmp_path)
    _run(rules_index, fixture)
    text = (fixture / "references" / "walk-design.md").read_text(encoding="utf-8")
    # T1-AAA-02 is phase: review-only and must never appear in the design walk.
    assert "T1-AAA-02" not in text


def test_meta_line_and_l2_no_phase_are_parsed_correctly(rules_index, root, tmp_path):
    """The real ruleset's convention: one `*meta:* pass=N order=M [phase=P]` bullet line, not
    the individual `pass:`/`order:`/`phase:` bullets an earlier draft of this fixture used."""
    fixture = _copy_fixture(root, tmp_path)
    _run(rules_index, fixture)
    index = json.loads((fixture / "rules.json").read_text(encoding="utf-8"))
    by_id = {r["id"]: r for r in index}
    assert by_id["T1-AAA-01"]["pass"] == 1
    assert by_id["T1-AAA-01"]["order"] == 1
    assert by_id["T1-AAA-01"]["phase"] == "6"
    assert by_id["T1-AAA-02"]["phase"] == "review-only"
    # T2-WID-01 carries pass/order (for the review walk) but no phase (§6: only L1 designs).
    assert by_id["T2-WID-01"]["pass"] == 1
    assert by_id["T2-WID-01"]["phase"] is None


def test_parent_and_absorbs_backticks_are_stripped(rules_index, root, tmp_path):
    fixture = _copy_fixture(root, tmp_path)
    _run(rules_index, fixture)
    index = json.loads((fixture / "rules.json").read_text(encoding="utf-8"))
    by_id = {r["id"]: r for r in index}
    assert by_id["T2-WID-01"]["parent"] == "T1-AAA-01"
    assert by_id["T2-WID-01"]["absorbs"] == ["K-WID-01"]
    assert by_id["T1-AAA-01"]["absorbs"] == ["U-ASR-01", "U-ASR-02"]


# ---------------------------------------------------------------------------
# Red-proofs: one per --check violation class, plus zero-rule and stale-walk.
# ---------------------------------------------------------------------------

def _append_rules(text: str, n: int, start: int) -> str:
    """n mechanically-valid, minimal T1 rules (own pass/order/phase, no parent needed)."""
    blocks = []
    for i in range(start, start + n):
        rid = f"T1-FIL-{i:02d}"
        blocks.append(
            f"\n**`{rid}` — Filler rule {i}.**\n"
            "- *design:* filler.\n- *review:* filler.\n- *check:* argued.\n"
            "- **severity:** minor · **evidence:** weak · **flag:** argued\n"
            f"- *meta:* pass=0 order={i} phase=review-only\n"
        )
    return text + "".join(blocks)


def test_l1_cap_violation(rules_index, root, tmp_path, capsys):
    fixture = _copy_fixture(root, tmp_path, "l1cap")
    universal = fixture / "references" / "universal.md"
    original = universal.read_text(encoding="utf-8")
    # 2 existing L1 rules + 39 filler = 41 > cap of 40.
    universal.write_text(_append_rules(original, 39, start=1), encoding="utf-8")

    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 1
    assert "[L1-CAP]" in out
    assert "41 exceeds the cap of 40" in out

    universal.write_text(original, encoding="utf-8")
    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 0


def test_missing_parent_violation(rules_index, root, tmp_path, capsys):
    fixture = _copy_fixture(root, tmp_path, "noparent")
    kind = fixture / "references" / "kind-widget.md"
    original = kind.read_text(encoding="utf-8")
    kind.write_text(
        original.replace(" · **parent:** `T1-AAA-01`", ""), encoding="utf-8")

    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 1
    assert "[NO-PARENT] T2-WID-01" in out

    kind.write_text(original, encoding="utf-8")
    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 0


def test_dangling_parent_violation(rules_index, root, tmp_path, capsys):
    fixture = _copy_fixture(root, tmp_path, "danglingparent")
    kind = fixture / "references" / "kind-widget.md"
    original = kind.read_text(encoding="utf-8")
    kind.write_text(original.replace("`T1-AAA-01`", "`T1-DOES-NOT-EXIST-99`"), encoding="utf-8")

    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 1
    assert "[BAD-PARENT] T2-WID-01" in out
    assert "T1-DOES-NOT-EXIST-99" in out

    kind.write_text(original, encoding="utf-8")
    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 0


def test_multi_id_parent_validates_every_named_id(rules_index, root, tmp_path, capsys):
    """A stack rule may specialise two ids at once (real example: T3-NET-41 `parent:`
    `T1-ORC-05`, `T1-SCO-01`) — each named id is checked, not just the first."""
    fixture = _copy_fixture(root, tmp_path, "multiparent")
    kind = fixture / "references" / "kind-widget.md"
    original = kind.read_text(encoding="utf-8")
    kind.write_text(
        original.replace("`T1-AAA-01`", "`T1-AAA-01`, `T1-GHOST-01`"), encoding="utf-8")

    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 1
    assert "[BAD-PARENT] T2-WID-01 parent: T1-GHOST-01" in out
    assert out.count("[BAD-PARENT]") == 1  # the valid T1-AAA-01 half is not also flagged

    kind.write_text(original, encoding="utf-8")
    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 0


def test_absorbs_not_in_manifest_violation(rules_index, root, tmp_path, capsys):
    fixture = _copy_fixture(root, tmp_path, "badabsorbs")
    universal = fixture / "references" / "universal.md"
    original = universal.read_text(encoding="utf-8")
    universal.write_text(
        original.replace("- *absorbs:* `U-ASR-01`, `U-ASR-02`\n",
                          "- *absorbs:* `U-ASR-01`, `U-ASR-02`, `U-INVENTED-99`\n"),
        encoding="utf-8")

    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 1
    assert "[BAD-ABSORBS] T1-AAA-01" in out
    assert "U-INVENTED-99" in out

    universal.write_text(original, encoding="utf-8")
    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 0


def test_absorbs_manifest_missing_entirely_is_also_a_violation(rules_index, root, tmp_path, capsys):
    fixture = _copy_fixture(root, tmp_path, "nomanifest")
    manifest = fixture / "lane-id-manifest.txt"
    manifest.unlink()

    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 1
    assert "[BAD-ABSORBS]" in out
    assert "lane-id-manifest.txt not found" in out


def test_dangling_cites_violation(rules_index, root, tmp_path, capsys):
    fixture = _copy_fixture(root, tmp_path, "badcites")
    universal = fixture / "references" / "universal.md"
    original = universal.read_text(encoding="utf-8")
    universal.write_text(
        original.replace("- *cites:* `governance.md`\n",
                          "- *cites:* `no-such-citation-file.md`\n", 1),
        encoding="utf-8")

    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 1
    assert "[BAD-CITES] T1-AAA-01" in out
    assert "no-such-citation-file.md" in out

    universal.write_text(original, encoding="utf-8")
    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 0


def test_dangling_invariant_citation_violation(rules_index, root, tmp_path, capsys):
    fixture = _copy_fixture(root, tmp_path, "badinvariant")
    universal = fixture / "references" / "universal.md"
    original = universal.read_text(encoding="utf-8")
    universal.write_text(
        original.replace("invariant `prove-the-check-fails`", "invariant `no-such-invariant`"),
        encoding="utf-8")

    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 1
    assert "[BAD-CITES] T1-AAA-02" in out
    assert "no-such-invariant" in out

    universal.write_text(original, encoding="utf-8")
    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 0


def test_weak_blocker_violation(rules_index, root, tmp_path, capsys):
    fixture = _copy_fixture(root, tmp_path, "weakblocker")
    universal = fixture / "references" / "universal.md"
    original = universal.read_text(encoding="utf-8")
    universal.write_text(
        original.replace(
            "- **severity:** major · **evidence:** weak · **flag:** argued\n",
            "- **severity:** blocker · **evidence:** weak · **flag:** argued\n", 1),
        encoding="utf-8")

    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 1
    assert "[WEAK-SEVERITY] T1-AAA-02" in out

    universal.write_text(original, encoding="utf-8")
    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 0


def test_weak_auto_flag_violation(rules_index, root, tmp_path, capsys):
    fixture = _copy_fixture(root, tmp_path, "weakauto")
    universal = fixture / "references" / "universal.md"
    original = universal.read_text(encoding="utf-8")
    universal.write_text(
        original.replace(
            "- **severity:** major · **evidence:** weak · **flag:** argued\n",
            "- **severity:** major · **evidence:** weak · **flag:** auto\n", 1),
        encoding="utf-8")

    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 1
    assert "[WEAK-SEVERITY] T1-AAA-02" in out
    assert "flag: auto" in out

    universal.write_text(original, encoding="utf-8")
    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 0


def test_bad_filename_violation(rules_index, root, tmp_path, capsys):
    fixture = _copy_fixture(root, tmp_path, "badfilename")
    bad = fixture / "references" / "kind-a11y.md"
    bad.write_text("# stray file — digit in the name (V3 / SYNTHESIS ruling G)\n", encoding="utf-8")

    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 1
    assert "[BAD-FILENAME] references/kind-a11y.md" in out

    bad.unlink()
    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 0


def test_zero_rules_violation(rules_index, root, tmp_path, capsys):
    fixture = _copy_fixture(root, tmp_path, "zerorules")
    refs = fixture / "references"
    for md in refs.glob("*.md"):
        md.write_text("# no rule headings here\n", encoding="utf-8")

    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 1
    assert "[ZERO-RULES]" in out


def test_planted_bogus_id_in_a_walk_is_caught_as_drift(rules_index, root, tmp_path, capsys):
    """SYNTHESIS ruling C: the gate's own test plants a bogus rule id in a walk, asserts red,
    removes it, asserts green — a walk that has only ever passed --check is not a check."""
    fixture = _copy_fixture(root, tmp_path, "bogusid")
    _run(rules_index, fixture)  # establish the committed baseline

    walk = fixture / "references" / "walk-review.md"
    original = walk.read_text(encoding="utf-8")
    walk.write_text(original + "- **T1-ZZZ-99** — a rule that does not exist. "
                                "(severity: blocker, flag: auto)\n",
                     encoding="utf-8")

    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 1
    assert "[STALE] references/walk-review.md" in out

    walk.write_text(original, encoding="utf-8")
    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 0


# ---------------------------------------------------------------------------
# A little parser robustness beyond the seven named classes.
# ---------------------------------------------------------------------------

def test_duplicate_id_is_flagged(rules_index, root, tmp_path, capsys):
    fixture = _copy_fixture(root, tmp_path, "dupid")
    universal = fixture / "references" / "universal.md"
    original = universal.read_text(encoding="utf-8")
    universal.write_text(original.replace("T1-AAA-02", "T1-AAA-01", 1), encoding="utf-8")

    rc, out = _run_captured(capsys, rules_index, fixture, "--check")
    assert rc == 1
    assert "[DUP-ID] T1-AAA-01" in out
