"""Tests for the managed .gitignore block scaffold.py merges into the target repo.

New capability (P0.5, SQLite storage migration): the scaffolder writes a marker-delimited
block into <target>/.gitignore for the task tracker's database and its WAL/SHM sidecars,
scoped to .ai-badger/task-tracking/ so the patterns anchor at the repo root. The block is
scaffold output — regenerated in place, never hand-owned; entries outside the markers are
the project's and must survive every merge.
"""
from __future__ import annotations

from conftest import _test_write

USER_ENTRIES = "node_modules/\n*.log\n"


def _block(text: str) -> str:
    """The managed block's interior of *text*, between (and excluding) the marker lines."""
    lines = text.splitlines()
    begin = next(i for i, l in enumerate(lines) if l.startswith("# BEGIN ai-badger"))
    end = next(i for i, l in enumerate(lines) if l.startswith("# END ai-badger"))
    return "\n".join(lines[begin + 1:end])


def test_first_scaffold_writes_the_managed_block(make_scaffolder):
    target = make_scaffolder.target
    assert not (target / ".gitignore").exists()

    make_scaffolder(skills=[]).run(generated_at="2026-07-19T00:00:00Z")

    text = (target / ".gitignore").read_text(encoding="utf-8")
    assert "# BEGIN ai-badger managed block" in text
    assert "# END ai-badger managed block" in text
    assert _block(text) == (
        ".ai-badger/task-tracking/tracking.db\n"
        ".ai-badger/task-tracking/*.db-wal\n"
        ".ai-badger/task-tracking/*.db-shm"
    )


def test_user_entries_outside_the_block_survive_the_merge(make_scaffolder):
    target = make_scaffolder.target
    _test_write(target / ".gitignore", USER_ENTRIES)

    make_scaffolder(skills=[]).run(generated_at="2026-07-19T00:00:00Z")

    text = (target / ".gitignore").read_text(encoding="utf-8")
    assert text.startswith(USER_ENTRIES), "user entries must come first, byte-preserved"
    assert "node_modules/" not in _block(text) and "*.log" not in _block(text)
    assert "tracking.db" in _block(text)


def test_rescaffold_is_idempotent_and_replaces_a_stale_block_in_place(make_scaffolder):
    """Intersection case: user entries + an existing (stale) block, then a re-scaffold.

    A second run must change nothing; a stale block (old artifact list, hand-edited
    interior) must be replaced in place — not duplicated, not appended around.
    """
    target = make_scaffolder.target
    _test_write(target / ".gitignore", USER_ENTRIES)
    make_scaffolder(skills=[]).run(generated_at="2026-07-19T00:00:00Z")
    after_first = (target / ".gitignore").read_text(encoding="utf-8")

    make_scaffolder(skills=[]).run(generated_at="2026-07-20T00:00:00Z")
    assert (target / ".gitignore").read_text(encoding="utf-8") == after_first

    stale = after_first.replace(".ai-badger/task-tracking/tracking.db\n", ".ai-badger/*.db\n")
    assert stale != after_first
    _test_write(target / ".gitignore", stale)

    make_scaffolder(skills=[]).run(generated_at="2026-07-21T00:00:00Z")

    text = (target / ".gitignore").read_text(encoding="utf-8")
    assert text.count("# BEGIN ai-badger managed block") == 1
    assert text.count("# END ai-badger managed block") == 1
    assert ".ai-badger/*.db" not in text
    assert _block(text) == (
        ".ai-badger/task-tracking/tracking.db\n"
        ".ai-badger/task-tracking/*.db-wal\n"
        ".ai-badger/task-tracking/*.db-shm"
    )
    assert text.startswith(USER_ENTRIES)


def test_unbalanced_markers_are_reported_not_rewritten(make_scaffolder):
    """Half a block says a hand edit is in flight; guessing could eat user entries."""
    target = make_scaffolder.target
    broken = USER_ENTRIES + "# BEGIN ai-badger managed block — do not edit; regenerated by welcome-ai-badger\n"
    _test_write(target / ".gitignore", broken)

    result = make_scaffolder(skills=[]).run(generated_at="2026-07-19T00:00:00Z")

    assert (target / ".gitignore").read_text(encoding="utf-8") == broken
    assert any("gitignore" in n for n in result["notes"])
