"""A hand edit to a generated file is refused at edit time, not at push time (D8/W10.e).

`.ai-badger/`, `.claude/` and the plugin's `skills/` tree are written by the scaffolder from
the `features/` catalog. Editing them by hand survives until the next scaffold and is then
reverted; `scaffold_freshness_guard` notices at push, hours after the work was done.

The oracle is `.ai-badger/manifest.json`, which the scaffolder writes: every generated file is
already recorded there with the source it came from. Nothing here guesses at a path shape.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path, PurePosixPath

import pytest
from conftest import _test_write

ROOT = Path(__file__).resolve().parents[1]
GUARD = "features/common/skills/welcome-ai-badger/scripts/generated_file_guard.py"
GUARD_PATH = ROOT / GUARD


@pytest.fixture(name="project")
def _project(tmp_path):
    """A project with a manifest, one generated skill, one catalog source and one plain file."""
    root = tmp_path / "proj"
    (root / ".ai-badger" / "skills" / "task" / "scripts").mkdir(parents=True)
    (root / "features" / "common" / "skills" / "task" / "scripts").mkdir(parents=True)
    (root / "skills" / "task").mkdir(parents=True)
    (root / "src").mkdir()
    _test_write(root / "src" / "app.py", "print(1)\n", encoding="utf-8")
    _test_write(root / ".ai-badger" / "manifest.json", json.dumps({"entries": [
        {"feature": "skills", "stack": "common",
         "source": "features/common/skills/task", "target": ".ai-badger/skills/task"},
        {"feature": "adjustments", "stack": "claude",
         "source": "features/claude/adjustments/adjust_agents.py",
         "target": ".claude/agents/architect.md"},
        {"feature": "adjustments", "stack": "claude",
         "source": "features/claude/adjustments/adjust_task.py",
         "target": ".ai-badger/skills/task/scripts/task_tracker.py"},
        {"feature": "templates", "stack": "common",
         "source": "features/common/templates/state.json", "target": ".ai-badger/state.json",
         "seedOnce": True},
        {"feature": "templates", "stack": "claude",
         "source": "features/claude/templates/CLAUDE.md.tmpl", "target": "CLAUDE.md"},
    ]}), encoding="utf-8")
    return root


def _drop_seed_once_flags(project):
    """Rewrite the manifest as a pre-0.101.0 scaffold left it: no `seedOnce` key anywhere."""
    path = project / ".ai-badger" / "manifest.json"
    document = json.loads(path.read_text(encoding="utf-8"))
    for entry in document["entries"]:
        entry.pop("seedOnce", None)
    _test_write(path, json.dumps(document), encoding="utf-8")


def _payload(path, tool="Edit"):
    key = "notebook_path" if tool == "NotebookEdit" else "file_path"
    return {"hook_event_name": "PreToolUse", "tool_name": tool, "tool_input": {key: str(path)}}


def _decision(guard, payload, capsys):
    """The guard's printed hook output as a dict, or None when it said nothing."""
    assert guard.decide(payload) == 0, "a PreToolUse gate must always exit 0"
    out = capsys.readouterr().out.strip()
    return json.loads(out) if out else None


def _denial_reason(guard, payload, capsys) -> str:
    decision = _decision(guard, payload, capsys)
    assert decision is not None, "the guard allowed an edit to a generated file"
    hook_output = decision["hookSpecificOutput"]
    assert hook_output["permissionDecision"] == "deny"
    return hook_output["permissionDecisionReason"]


def test_a_sibling_sharing_a_manifest_targets_name_prefix_is_not_generated(
        load_script, project, capsys):
    """`.ai-badger/skills/task-force/` is not inside `.ai-badger/skills/task`.

    Containment is a path-segment question, and every other fixture here compares paths that
    either match exactly or diverge at the first character — so dropping the `+ "/"` boundary
    from the predicate and matching a bare string prefix changed no test's verdict.
    """
    guard = load_script(GUARD)
    sibling = project / ".ai-badger" / "skills" / "task-force" / "notes.py"
    sibling.parent.mkdir(parents=True)
    _test_write(sibling, "# hand-written, generated by nothing\n", encoding="utf-8")

    assert guard.manifest_source(project, PurePosixPath(
        ".ai-badger/skills/task-force/notes.py")) is None
    assert _decision(guard, _payload(sibling), capsys) is None, \
        "the guard refused an edit to a directory that merely starts with a generated one"


def test_editing_a_generated_skill_file_is_refused_and_names_its_catalog_source(
        load_script, project, capsys):
    guard = load_script(GUARD)
    target = project / ".ai-badger" / "skills" / "task" / "scripts" / "tracker_lib.py"

    reason = _denial_reason(guard, _payload(target), capsys)

    assert ".ai-badger/skills/task/scripts/tracker_lib.py is generated" in reason, \
        "the refusal must name the file the agent tried to edit, not the manifest target dir"
    assert "features/common/skills/task/scripts/tracker_lib.py" in reason
    assert "welcome-ai-badger" in reason


def test_the_most_specific_manifest_entry_names_the_source(load_script, project, capsys):
    """A file inside a generated skill can have a generator of its own; the skill is not it."""
    guard = load_script(GUARD)
    target = project / ".ai-badger" / "skills" / "task" / "scripts" / "task_tracker.py"

    reason = _denial_reason(guard, _payload(target), capsys)

    assert "features/claude/adjustments/adjust_task.py" in reason
    assert "features/common/skills/task/scripts/task_tracker.py" not in reason


def test_editing_a_copied_agent_file_is_refused(load_script, project, capsys):
    """`.claude/agents/*.md` is written by an adjustment, and the manifest records which one."""
    guard = load_script(GUARD)

    reason = _denial_reason(guard, _payload(project / ".claude" / "agents" / "architect.md"),
                            capsys)

    assert "features/claude/adjustments/adjust_agents.py" in reason


def test_editing_the_plugin_copy_of_a_skill_is_refused(load_script, project, capsys):
    """`skills/` is not in the manifest; it is `sync_plugin_skills.py`'s copy of the catalog."""
    guard = load_script(GUARD)

    reason = _denial_reason(guard, _payload(project / "skills" / "task" / "SKILL.md"), capsys)

    assert "features/common/skills/task/SKILL.md" in reason
    assert "sync_plugin_skills" in reason


def test_a_projects_own_skills_directory_is_left_alone(load_script, project, capsys):
    """A consumer repo's `skills/` is its own source. Only a name the catalog also holds is a copy."""
    guard = load_script(GUARD)
    theirs = project / "skills" / "their-own-thing" / "SKILL.md"
    theirs.parent.mkdir(parents=True)

    assert _decision(guard, _payload(theirs), capsys) is None


@pytest.mark.parametrize("tool", ["Edit", "Write", "MultiEdit", "NotebookEdit"])
def test_every_edit_shaped_tool_is_covered(load_script, project, capsys, tool):
    guard = load_script(GUARD)
    target = project / ".ai-badger" / "skills" / "task" / "SKILL.md"

    _denial_reason(guard, _payload(target, tool=tool), capsys)


def test_an_ordinary_source_file_is_allowed(load_script, project, capsys):
    guard = load_script(GUARD)

    assert _decision(guard, _payload(project / "src" / "app.py"), capsys) is None


def test_the_catalog_itself_is_allowed(load_script, project, capsys):
    """The whole point of the denial is to send the edit here."""
    guard = load_script(GUARD)
    target = project / "features" / "common" / "skills" / "task" / "scripts" / "tracker_lib.py"

    assert _decision(guard, _payload(target), capsys) is None


def test_a_seeded_template_is_allowed(load_script, project, capsys):
    """`.ai-badger/state.json` carries `seedOnce`: seeded once, owned by the project after."""
    guard = load_script(GUARD)

    assert _decision(guard, _payload(project / ".ai-badger" / "state.json"), capsys) is None


def test_a_template_the_next_scaffold_rewrites_is_refused(load_script, project, capsys):
    """Five of this repo's seven `templates` targets are rewritten on every scaffold.

    Exempting the whole feature let an agent edit CLAUDE.md, lose it to the next scaffold and
    then have the push rejected as hand-edited — the failure the guard exists to prevent.
    """
    guard = load_script(GUARD)

    reason = _denial_reason(guard, _payload(project / "CLAUDE.md"), capsys)

    assert "features/claude/templates/CLAUDE.md.tmpl" in reason
    assert "welcome-ai-badger" in reason


def test_a_manifest_older_than_the_flag_refuses_rather_than_exempts(load_script, project,
                                                                    capsys):
    """A pre-0.101.0 manifest cannot tell the two apart, so the guard fails closed.

    The plugin's copy of this guard updates when the plugin does, not when a project
    re-scaffolds, so guard-newer-than-manifest is reachable. Refusing an edit is loud, names
    its override lever and self-heals on the next scaffold; exempting is silent and costs the
    push cycle this guard was added to remove.
    """
    guard = load_script(GUARD)
    _drop_seed_once_flags(project)

    _denial_reason(guard, _payload(project / ".ai-badger" / "state.json"), capsys)
    _denial_reason(guard, _payload(project / "CLAUDE.md"), capsys)


def test_a_file_outside_any_ai_badger_project_is_allowed(load_script, tmp_path, capsys):
    guard = load_script(GUARD)
    stray = tmp_path / "unrelated" / ".ai-badger" / "skills" / "x.md"
    stray.parent.mkdir(parents=True)

    assert _decision(guard, _payload(stray), capsys) is None


def test_a_non_edit_tool_is_allowed(load_script, project, capsys):
    """The scaffolder writes through Bash, never through an edit tool."""
    guard = load_script(GUARD)
    payload = {"tool_name": "Bash",
               "tool_input": {"command": "python3 tooling/scaffold.py --target ."}}

    assert _decision(guard, payload, capsys) is None


def test_the_override_lever_allows_a_deliberate_hand_patch(load_script, project, capsys,
                                                           monkeypatch):
    guard = load_script(GUARD)
    monkeypatch.setenv(guard.OVERRIDE_ENV, "1")
    target = project / ".ai-badger" / "skills" / "task" / "SKILL.md"

    assert _decision(guard, _payload(target), capsys) is None


def test_a_corrupt_manifest_fails_open(load_script, project, capsys):
    """A guard that denies on its own internal error would brick every edit in the repo."""
    guard = load_script(GUARD)
    _test_write(project / ".ai-badger" / "manifest.json", "{not json", encoding="utf-8")
    target = project / ".ai-badger" / "skills" / "task" / "SKILL.md"

    assert _decision(guard, _payload(target), capsys) is None


def test_garbage_on_stdin_exits_zero_and_says_nothing():
    """`main()` is the surface Claude Code actually invokes."""
    result = subprocess.run([sys.executable, str(GUARD_PATH)], input="not json at all",
                            capture_output=True, text=True, check=False)

    assert result.returncode == 0
    assert result.stdout.strip() == ""


def test_the_guard_denies_end_to_end_through_stdin(project):
    """The real invocation shape: JSON in on stdin, a deny decision out on stdout."""
    target = project / ".ai-badger" / "skills" / "task" / "SKILL.md"

    result = subprocess.run([sys.executable, str(GUARD_PATH)],
                            input=json.dumps(_payload(target)),
                            capture_output=True, text=True, check=False)

    assert result.returncode == 0
    decision = json.loads(result.stdout)["hookSpecificOutput"]
    assert decision["permissionDecision"] == "deny"
    assert "features/common/skills/task/SKILL.md" in decision["permissionDecisionReason"]


# ------------------------------------------------- the files inside a skill the project owns
# The scaffolder preserves `project-local.md` and every SEED_ONCE_SKILL_FILES entry across a
# re-scaffold, so `scaffold_freshness_guard` passes a project that hand-edits them. Denying
# them at edit time contradicted the push-time gate the guard exists to mirror. The manifest
# names them per skill entry (`projectOwned`), so the guard reads one source of truth.
def _declare_project_owned(project, target, names):
    """Stamp `projectOwned` onto the manifest entry whose target is exactly *target*."""
    path = project / ".ai-badger" / "manifest.json"
    document = json.loads(path.read_text(encoding="utf-8"))
    for entry in document["entries"]:
        if entry.get("target") == target:
            entry["projectOwned"] = names
    _test_write(path, json.dumps(document), encoding="utf-8")


def test_a_project_owned_file_inside_a_generated_skill_is_allowed(load_script, project, capsys):
    guard = load_script(GUARD)
    _declare_project_owned(project, ".ai-badger/skills/task",
                           ["project-local.md", "markers-context.json"])
    skill = project / ".ai-badger" / "skills" / "task"

    for name in ("project-local.md", "markers-context.json"):
        assert _decision(guard, _payload(skill / name), capsys) is None, \
            f"the guard refused an edit to {name}, which the scaffold preserves"


def test_the_generated_files_in_that_same_skill_are_still_denied(load_script, project, capsys):
    """Over-correction check: one project-owned file must not exempt its whole directory."""
    guard = load_script(GUARD)
    _declare_project_owned(project, ".ai-badger/skills/task", ["project-local.md"])
    skill = project / ".ai-badger" / "skills" / "task"

    assert "features/common/skills/task/SKILL.md" in _denial_reason(
        guard, _payload(skill / "SKILL.md"), capsys)
    assert "features/common/skills/task/scripts/run.py" in _denial_reason(
        guard, _payload(skill / "scripts" / "run.py"), capsys)


def test_a_file_the_manifest_does_not_list_as_project_owned_is_denied(load_script, project,
                                                                     capsys):
    """The list is read, not assumed: a name absent from it stays generated."""
    guard = load_script(GUARD)
    _declare_project_owned(project, ".ai-badger/skills/task", ["markers-context.json"])
    skill = project / ".ai-badger" / "skills" / "task"

    assert "features/common/skills/task/project-local.md" in _denial_reason(
        guard, _payload(skill / "project-local.md"), capsys)


def test_project_owned_does_not_reach_a_sibling_skill(load_script, project, capsys):
    """Entries are per skill; one skill's list must not exempt another skill's copy."""
    guard = load_script(GUARD)
    path = project / ".ai-badger" / "manifest.json"
    document = json.loads(path.read_text(encoding="utf-8"))
    document["entries"].append({
        "feature": "skills", "stack": "common",
        "source": "features/common/skills/prompt-markers",
        "target": ".ai-badger/skills/prompt-markers"})
    _test_write(path, json.dumps(document), encoding="utf-8")
    _declare_project_owned(project, ".ai-badger/skills/task", ["markers-context.json"])
    sibling = project / ".ai-badger" / "skills" / "prompt-markers" / "markers-context.json"

    assert "features/common/skills/prompt-markers/markers-context.json" in _denial_reason(
        guard, _payload(sibling), capsys)


def test_a_more_specific_generated_entry_still_wins_over_project_owned(load_script, project,
                                                                      capsys):
    """An adjustment writes .../scripts/task_tracker.py; naming it project-owned on the
    directory entry must not beat the entry that actually generates it."""
    guard = load_script(GUARD)
    _declare_project_owned(project, ".ai-badger/skills/task", ["scripts/task_tracker.py"])
    target = project / ".ai-badger" / "skills" / "task" / "scripts" / "task_tracker.py"

    assert "adjust_task.py" in _denial_reason(guard, _payload(target), capsys)


def test_a_manifest_written_before_project_owned_denies_rather_than_crashing(load_script,
                                                                            project, capsys):
    """The pre-0.107.0 manifest carries no list: a loud refusal that self-heals on re-scaffold."""
    guard = load_script(GUARD)
    target = project / ".ai-badger" / "skills" / "task" / "project-local.md"

    assert "features/common/skills/task/project-local.md" in _denial_reason(
        guard, _payload(target), capsys)


def test_a_malformed_project_owned_value_is_ignored(load_script, project, capsys):
    """A hand-mangled manifest must not make the guard throw — it exempts nothing instead."""
    guard = load_script(GUARD)
    _declare_project_owned(project, ".ai-badger/skills/task", "project-local.md")
    target = project / ".ai-badger" / "skills" / "task" / "project-local.md"

    assert _denial_reason(guard, _payload(target), capsys)


def test_the_skill_directory_itself_is_never_project_owned(load_script, project, capsys):
    """The empty remainder must not match an empty-string entry someone slipped into the list."""
    guard = load_script(GUARD)
    _declare_project_owned(project, ".ai-badger/skills/task", [""])
    target = project / ".ai-badger" / "skills" / "task"

    assert _denial_reason(guard, _payload(target), capsys)
