"""Tests for the gates/ layout: the repo gates live, run and get linted from one place."""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Set

GATE_NAMES = ("deps_guard.py", "docs_guard.py", "release_guard.py",
              "scaffold_freshness_guard.py", "shipped_paths_guard.py", "tdd_guard.py")

# Top-level directories holding *.py we do not author: mirrors of features/, regenerated by
# tooling/sync_plugin_skills.py and the scaffolder.
GENERATED_PY_ROOTS = frozenset({".ai-badger", ".claude", "skills"})

# tests/ is exempt by policy, not by oversight: CONTRIBUTING.md says tests keep their own
# conventions, and every runner selects with `grep -v '^tests/'`.
LINT_EXEMPT_PY_ROOTS = GENERATED_PY_ROOTS | {"tests"}

# The one file selection every lint runner shares: CI, the lefthook pylint lane, and the
# documented `lint` command. One lint behaviour everywhere — issue #183.
LINT_SELECTION = "git ls-files '*.py' | grep -v '^tests/'"
LINT_RUNNERS = (".github/workflows/pylint.yml", ".lefthook/pre-push/verify.sh")


def _tracked_python_roots(root: Path) -> Set[str]:
    out = subprocess.run(["git", "ls-files", "*.py"], cwd=str(root), capture_output=True,
                         text=True, check=True).stdout
    roots = {line.split("/")[0] for line in out.splitlines() if "/" in line}
    return roots - LINT_EXEMPT_PY_ROOTS


def test_every_gate_lives_in_the_gates_directory(root):
    """A gate outside gates/ is a gate the pylint target and CI lane can silently miss."""
    assert sorted(p.name for p in (root / "gates").glob("*_guard.py")) == sorted(GATE_NAMES)
    for elsewhere in ("engine", "tooling"):
        assert sorted(p.name for p in (root / elsewhere).glob("*_guard.py")) == []


def test_every_gate_runs_from_its_new_home(root):
    """Each gate resolves badger_lib after the move; an ImportError here is the whole risk."""
    for name in GATE_NAMES:
        proc = subprocess.run([sys.executable, str(root / "gates" / name), "--help"],
                              cwd=str(root), capture_output=True, text=True, check=False)
        combined = proc.stdout + proc.stderr
        assert proc.returncode == 0, f"{name}: exit {proc.returncode}\n{combined}"
        assert "Traceback" not in combined, f"{name}: {combined}"
        assert "ImportError" not in combined, f"{name}: {combined}"


def _documented_lint_command(root: Path) -> str:
    config = json.loads((root / ".ai-badger" / "config.json").read_text(encoding="utf-8"))
    return config["commands"]["lint"]


def test_documented_lint_command_enumerates_files_like_ci(root):
    """Package mode reported 10.00 while CI failed; the documented command is the one agents run."""
    command = _documented_lint_command(root)
    assert command.startswith("python3 -m pylint "), command
    assert f"$({LINT_SELECTION})" in command, command


def test_ci_and_lefthook_select_the_same_files_as_the_documented_command(root):
    """Three runners, one selection string — a divergence here is a gate that passes locally."""
    for relative in LINT_RUNNERS:
        text = (root / relative).read_text(encoding="utf-8")
        assert LINT_SELECTION in text, f"{relative} does not use the shared lint selection"


def test_lint_selection_covers_every_directory_holding_our_python(root):
    """Rewrite of test_every_gate_is_a_pylint_target: enumeration replaced named directories."""
    selected = subprocess.run(["/bin/sh", "-c", LINT_SELECTION], cwd=str(root),
                              capture_output=True, text=True, check=True).stdout.splitlines()
    assert selected, "the lint selection matched nothing"
    roots = {line.split("/")[0] for line in selected if "/" in line}
    missing = sorted(_tracked_python_roots(root) - roots)
    assert not missing, f"unlinted directories holding our *.py: {missing}"
    assert "tests" not in roots
