#!/usr/bin/env python3
"""PreToolUse gate on the derived trees: a generated file is edited at its source, not in place.

`.ai-badger/`, `.claude/` and the plugin's `skills/` tree are written by the scaffolder from the
`features/` catalog, so a hand edit there lives until the next scaffold and is then reverted.
`gates/scaffold_freshness_guard.py` catches that at push time; this moves it to edit time.

The oracle is `.ai-badger/manifest.json`, which the scaffold writes: every generated file is
already recorded there against the source it came from. Nothing here infers a path shape.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path, PurePosixPath
from typing import Any, Dict, Optional, Tuple

EDIT_TOOLS = ("Edit", "Write", "MultiEdit", "NotebookEdit")
OVERRIDE_ENV = "AI_BADGER_ALLOW_GENERATED_EDITS"
MANIFEST = ".ai-badger/manifest.json"

# Manifest features whose targets the scaffold rewrites on every run. `templates` is deliberately
# absent: a template is seeded once and then belongs to the project (`.ai-badger/state.json`,
# `CLAUDE.md`), so refusing to edit one would refuse the intended way to use it.
REGENERATED_FEATURES = frozenset({"skills", "personas", "instructions", "invariants",
                                  "adjustments"})

# The plugin copy under `skills/` is produced by tooling/sync_plugin_skills.py, which writes no
# manifest. It is only a copy when the catalog it was copied from is still there to prove it.
PLUGIN_TREE = "skills"
CATALOG_SKILL_BASES = ("features/common/skills", "features/claude/skills")

DENY_REASON = (
    "{target} is generated by ai-badger; the next scaffold overwrites it, so this edit is lost. "
    "Edit {source} instead, then re-run {regenerate}. "
    "Set {override}=1 for a deliberate one-off hand patch."
)


def edited_path(payload: Dict[str, Any]) -> Optional[str]:
    """The file an edit-shaped tool call targets, or None when this call is not one."""
    if not isinstance(payload, dict):
        return None
    if (payload.get("tool_name") or payload.get("toolName")) not in EDIT_TOOLS:
        return None
    tool_input = payload.get("tool_input") or payload.get("toolInput") or {}
    if not isinstance(tool_input, dict):
        return None
    path = tool_input.get("file_path") or tool_input.get("notebook_path")
    return path if isinstance(path, str) and path.strip() else None


def project_of(path: Path) -> Optional[Path]:
    """The nearest ancestor of *path* carrying a scaffold manifest.

    Derived from the edited file, never from the cwd or `$CLAUDE_PROJECT_DIR`: in a worktree
    session those name the main checkout while the edit lands in the worktree.
    """
    for ancestor in path.parents:
        if (ancestor / MANIFEST).is_file():
            return ancestor
    return None


def manifest_entries(root: Path) -> list:
    """The manifest's entries, or an empty list when it is absent or unreadable."""
    try:
        document = json.loads((root / MANIFEST).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return []
    entries = document.get("entries") if isinstance(document, dict) else None
    return entries if isinstance(entries, list) else []


def _under(rel: PurePosixPath, target: str) -> bool:
    return str(rel) == target or str(rel).startswith(target + "/")


def manifest_source(root: Path, rel: PurePosixPath) -> Optional[Tuple[str, str]]:
    """(target, source) for the regenerated manifest entry covering *rel*, longest match first."""
    best: Optional[Tuple[str, str]] = None
    for entry in manifest_entries(root):
        if not isinstance(entry, dict) or entry.get("feature") not in REGENERATED_FEATURES:
            continue
        target, source = entry.get("target"), entry.get("source")
        if not isinstance(target, str) or not isinstance(source, str) or not _under(rel, target):
            continue
        if best is None or len(target) > len(best[0]):
            best = (target, source)
    if best is None:
        return None
    target, source = best
    remainder = str(rel)[len(target):].lstrip("/")
    return target, f"{source}/{remainder}" if remainder else source


def plugin_copy_source(root: Path, rel: PurePosixPath) -> Optional[str]:
    """The catalog path *rel* was copied from when it sits in the plugin's `skills/` tree."""
    parts = rel.parts
    if len(parts) < 2 or parts[0] != PLUGIN_TREE:
        return None
    for base in CATALOG_SKILL_BASES:
        if (root / base / parts[1]).is_dir():
            return "/".join((base, *parts[1:]))
    return None


def refusal(path: Path) -> Optional[str]:
    """The reason to refuse an edit to *path*, or None when it is not a generated file."""
    root = project_of(path)
    if root is None:
        return None
    try:
        rel = PurePosixPath(path.relative_to(root).as_posix())
    except ValueError:  # pragma: no cover - project_of only returns ancestors
        return None

    found = manifest_source(root, rel)
    if found is not None:
        source, regenerate = found[1], "welcome-ai-badger (or den-refresh)"
    else:
        source = plugin_copy_source(root, rel)
        if source is None:
            return None
        regenerate = "tooling/sync_plugin_skills.py"
    return DENY_REASON.format(target=rel, source=source, regenerate=regenerate,
                              override=OVERRIDE_ENV)


def decide(payload: Dict[str, Any]) -> int:
    """Print a deny decision iff an edit-shaped call targets a file the scaffold owns."""
    if os.environ.get(OVERRIDE_ENV, "").strip():
        return 0
    path = edited_path(payload)
    if path is None:
        return 0
    reason = refusal(Path(path).expanduser().resolve())
    if reason is None:
        return 0
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": reason,
        }
    }))
    return 0


def main() -> int:
    """Read the hook payload from stdin. Fails open: a broken guard must never brick editing."""
    try:
        return decide(json.load(sys.stdin))
    except Exception:  # pylint: disable=broad-exception-caught
        return 0


if __name__ == "__main__":
    sys.exit(main())
