#!/usr/bin/env python3
"""Generate rules.json and the two ruleset walks from references/*.md; --check verifies.

Markdown is the source of truth (MoE-2-ruleset.md §3.3, SYNTHESIS.md ruling C). Every rule in
`references/{principles,universal,kind-*,stack-*}.md` is a heading — one of

    #### `<id>` — <title>            (stack-dotnet.md's convention)
    **`<id>` — <title>**             (universal.md / kind-*.md's convention)
    **`<id>`** — <title>             (principles.md's convention — bold wraps only the id)

followed by a fixed bullet block of `- key: value` lines (asterisk/backtick decoration around
the key is tolerated and stripped; several `key: value` pairs may share one line separated by
`·`, e.g. `- **severity:** blocker · **evidence:** strong · **flag:** argued`). Recognised keys:
design, review, check, severity, evidence, flag, parent, absorbs, cites, archetypes, invariant,
retired, and the single machine-read line

    - *meta:* pass=<0-8> order=<int> phase=<1-8 or review-only>

(universal.md's own header names this "the machine-read line": `pass`/`order` place a rule in
`walk-review.md`, `phase` places it in `walk-design.md`). Only L1 rules carry `phase` — per
MoE-2-ruleset.md §6, "Same 40 rules" populate the design walk, never a kind/stack specialisation.
`parent`/`invariant` are single ids, or — rarely, on a stack rule that specialises two L1/L2
rules at once — a comma-separated list; every named id is checked individually. L0 principles
(`T0-nn`, no group segment) carry only `title` and, optionally, `cites` — MoE-2-ruleset.md §1.4
is explicit that a principle is invariant-style, not rule-style, and has no `check`. They are
parsed into rules.json for lookup but never placed in a walk.

This script emits three committed artefacts, in `references/` unless noted:
  - `../rules.json`     — one record per rule: id, layer, group, title, severity, evidence,
                          flag, parent, absorbs[], archetypes[], pass, order, phase, file, line.
                          No prose, ever — the moment a rationale is written into it, it is a
                          second source of truth and must be deleted (MoE-2-ruleset.md §3.3).
  - `walk-review.md`    — passes 0-8, rules ordered by (pass, order); a rule whose `parent:`
                          shares its parent's pass renders indented under it.
  - `walk-design.md`    — steps 1-8 from `phase:`, omitting `phase: review-only`.

`--check` regenerates all three in memory and fails when a committed copy differs (drift), and
additionally fails on:
  1. a live (non-retired) L1 rule count above the cap of 40
  2. a L2/L3 rule (`T2-*`/`T3-*`) with no `parent:`
  3. a `parent:` naming an id that does not exist anywhere in the parsed set
  4. an `absorbs:` id that is neither in `<root>/lane-id-manifest.txt` nor a known rule id
  5. a `cites:` naming a repo file (backtick, `*.md`) or `invariant \\`<slug>\\`` whose
     `.ai-badger/invariants/<slug>.md` is not found anywhere under the repo anchor
  6. a `weak`-evidence rule carrying `severity: blocker` or `flag: auto`
  7. a file directly under `references/` whose name does not match `^[a-z][a-z-]*\\.md$`
  and on a parsed-rule count of zero (an index built from a moved/renamed directory must not
  report a clean, empty pass — MoE-2-ruleset.md §3.3, "prove the checker fails").

Per `feedback-regenerate-dont-fail.md`, the two modes differ only in what happens once the
structural checks (1-7, zero-count) pass: no-flag mode writes the regenerated artefacts
unconditionally (fit for a pre-commit hook); `--check` mode never writes, and additionally
diffs the in-memory output against the three committed files (fit for CI). A structural
violation blocks writing in *either* mode — regeneration cannot repair an authoring error, only
drift.

Usage: rules_index.py [--root <skill-dir>] [--check]
  --root  : the review-tests skill directory (default: this script's own skill directory,
            i.e. the parent of scripts/). Tests point it at a fixture skill directory.
  --check : do not write; exit 1 on any structural violation or on drift, exit 0 when clean.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional

GENERATED_BANNER = (
    "<!-- generated by scripts/rules_index.py — do not edit; "
    "edit the rule's meta: line instead -->"
)

# T0-01 (no group) | T1-SCO-01 / T2-WID-01 / T3-NET-01 (layer-group-nn) | TX-EXC-01 (L4 project-local)
ID_RE = r"T(?:0-\d{2}|[1-4]-[A-Z0-9]+-\d{2}|X-[A-Z0-9]+-\d{2})"
# The `\*{0,2}` right after the id absorbs principles.md's "bold wraps only the id" shape
# (`**`T0-01`** — title`) as well as the plain ATX and "bold wraps the whole heading" shapes.
HEADING_RE = re.compile(
    rf"^(?:#{{2,4}}\s+|\*\*)`?(?P<id>{ID_RE})`?\*{{0,2}}\s*[—–-]\s*(?P<title>.+?)\*{{0,2}}\s*$"
)
FIELD_SEG_RE = re.compile(r"^\*{0,2}([A-Za-z]+):\*{0,2}\s*(.*)$")
FILENAME_RE = re.compile(r"^[a-z][a-z-]*\.md$")
INVARIANT_CITE_RE = re.compile(r"invariant\s+`([a-z0-9-]+)`")
FILE_CITE_RE = re.compile(r"`([\w./-]+\.md)`")

GENERATED_WALK_FILES = {"walk-review.md", "walk-design.md"}
L1_CAP = 40
PASSES = list(range(9))          # 0..8
DESIGN_STEPS = list(range(1, 9))  # 1..8


@dataclass
class Rule:
    """One parsed rule record. `pass_`/`order`/`phase` are the SYNTHESIS.md ruling-C fields
    that place the rule in a generated walk; they are absent (None) for L0 principles."""

    id: str
    title: str
    file: str
    line: int
    severity: Optional[str] = None
    evidence: Optional[str] = None
    flag: Optional[str] = None
    design: Optional[str] = None
    review: Optional[str] = None
    check: Optional[str] = None
    parent: Optional[str] = None
    absorbs: List[str] = field(default_factory=list)
    cites: Optional[str] = None
    archetypes: List[str] = field(default_factory=list)
    invariant: Optional[str] = None
    retired: Optional[str] = None
    pass_: Optional[int] = None
    order: Optional[int] = None
    phase: Optional[str] = None  # "1".."8" or "review-only"

    @property
    def layer(self):
        parts = self.id.split("-")
        return parts[0][1:]  # "0", "1", "2", "3", "4", "X"

    @property
    def group(self):
        parts = self.id.split("-")
        return parts[1] if len(parts) == 3 else None

    @property
    def is_retired(self) -> bool:
        return bool(self.retired)


# ---------------------------------------------------------------------------
# Parsing — line-oriented, no third-party deps (ADR-0005: no pyyaml).
# ---------------------------------------------------------------------------

def _split_field_line(line: str) -> List[tuple]:
    """A `- key: value[ · key: value ...]` bullet line to a list of (key, value) pairs."""
    body = line.strip()
    if not body.startswith("-"):
        return []
    body = body[1:].strip()
    segments = [s.strip() for s in body.split("·") if s.strip()] or [body]
    pairs = []
    for seg in segments:
        m = FIELD_SEG_RE.match(seg)
        if not m:
            continue
        key = m.group(1).lower()
        val = m.group(2).strip().strip("*").strip()
        pairs.append((key, val))
    return pairs


_LIST_FIELDS = {"absorbs", "archetypes"}
_INT_FIELDS = {"pass", "order"}
_BACKTICK_ID_FIELDS = {"parent", "invariant"}  # single/comma-separated ids, never free prose


def _strip_backticks(text: str) -> str:
    return text.replace("`", "").strip()


def _apply_meta(rule: Rule, val: str) -> None:
    """`- *meta:* pass=3 order=14 phase=7` — the machine-read line every kind/stack lane uses
    (universal.md's own header names it that). Space-separated `key=value` tokens; any subset."""
    for token in val.split():
        if "=" not in token:
            continue
        k, v = token.split("=", 1)
        k, v = k.strip().lower(), v.strip()
        if k == "pass":
            rule.pass_ = int(v) if v else None
        elif k == "order":
            rule.order = int(v) if v else None
        elif k == "phase":
            rule.phase = v or None


def _apply_field(rule: Rule, key: str, val: str) -> None:
    if key == "meta":
        _apply_meta(rule, val)
        return
    if key in _LIST_FIELDS:
        items = [_strip_backticks(v) for v in val.split(",") if v.strip()]
        setattr(rule, key, items)
        return
    if key == "pass":
        rule.pass_ = int(val) if val else None
        return
    if key in _INT_FIELDS:
        setattr(rule, key, int(val) if val else None)
        return
    if key in _BACKTICK_ID_FIELDS:
        setattr(rule, key, _strip_backticks(val))
        return
    if key in ("id", "title", "file", "line", "layer", "group"):
        return  # derived / already set, not settable via a bullet line
    if hasattr(rule, key):
        setattr(rule, key, val)


def parse_file(path: Path, root: Path) -> List[Rule]:
    """Parse every `#### <id> — <title>` record in one references/*.md file."""
    text = path.read_text(encoding="utf-8")
    relpath = path.relative_to(root).as_posix()
    rules: List[Rule] = []
    current: Optional[Rule] = None
    for lineno, raw in enumerate(text.splitlines(), start=1):
        m = HEADING_RE.match(raw.strip())
        if m:
            current = Rule(id=m.group("id"), title=m.group("title").strip(),
                            file=relpath, line=lineno)
            rules.append(current)
            continue
        if current is None:
            continue
        if raw.strip() == "---":
            current = None
            continue
        for key, val in _split_field_line(raw):
            _apply_field(current, key, val)
    return rules


def parse_tree(root: Path) -> List[Rule]:
    """Parse every references/*.md rule file under `root`, excluding the generated walks."""
    refs = root / "references"
    if not refs.is_dir():
        return []
    rules: List[Rule] = []
    for path in sorted(refs.glob("*.md")):
        if path.name in GENERATED_WALK_FILES:
            continue
        rules.extend(parse_file(path, root))
    return rules


# ---------------------------------------------------------------------------
# Structural checks — the seven `--check` violation classes plus zero-count.
# ---------------------------------------------------------------------------

def _repo_anchor(root: Path) -> Path:
    """Walk up from `root` to the nearest repo marker; fall back to `root` itself.

    Hermetic by construction: a fixture with no `.git`/`VERSION`/`.ai-badger` above it
    anchors on itself, so citation resolution never reaches outside the tree under test.
    """
    cur = root
    for _ in range(6):
        if (cur / ".git").exists() or (cur / "VERSION").exists() or (cur / ".ai-badger").exists():
            return cur
        if cur.parent == cur:
            break
        cur = cur.parent
    return root


def _citation_exists(anchor: Path, relpath: str) -> bool:
    direct = anchor / relpath
    if direct.exists():
        return True
    name = Path(relpath).name
    for p in anchor.rglob(name):
        if ".git" in p.parts:
            continue
        return True
    return False


def check_l1_cap(rules: List[Rule]) -> List[str]:
    live = [r for r in rules if r.layer == "1" and not r.is_retired]
    if len(live) > L1_CAP:
        return [f"[L1-CAP] live L1 rule count {len(live)} exceeds the cap of {L1_CAP}"]
    return []


def check_missing_parent(rules: List[Rule]) -> List[str]:
    out = []
    for r in rules:
        if r.layer in ("2", "3") and not r.parent:
            out.append(f"[NO-PARENT] {r.id} is L{r.layer} and carries no parent:")
    return out


def check_dangling_parent(rules: List[Rule]) -> List[str]:
    """`parent:` is normally one id (§3.1); a handful of stack rules specialise two (comma-
    separated) — every named id must resolve, individually."""
    known = {r.id for r in rules}
    out = []
    for r in rules:
        if not r.parent:
            continue
        for pid in (p.strip() for p in r.parent.split(",")):
            if pid and pid not in known:
                out.append(f"[BAD-PARENT] {r.id} parent: {pid} does not resolve to a parsed rule")
    return out


def _load_manifest(root: Path) -> Optional[set]:
    manifest_path = root / "lane-id-manifest.txt"
    if not manifest_path.exists():
        return None
    ids = set()
    for line in manifest_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        ids.add(line)
    return ids


def check_absorbs_manifest(root: Path, rules: List[Rule]) -> List[str]:
    manifest = _load_manifest(root)
    if manifest is None:
        if any(r.absorbs for r in rules):
            return ["[BAD-ABSORBS] lane-id-manifest.txt not found — cannot validate absorbs: ids"]
        return []
    known_ids = {r.id for r in rules}
    out = []
    for r in rules:
        for aid in r.absorbs:
            if aid not in manifest and aid not in known_ids:
                out.append(f"[BAD-ABSORBS] {r.id} absorbs: {aid} is in neither "
                            f"lane-id-manifest.txt nor the parsed rule set")
    return out


def check_cites(root: Path, rules: List[Rule]) -> List[str]:
    anchor = _repo_anchor(root)
    out = []
    for r in rules:
        if not r.cites:
            continue
        for slug in INVARIANT_CITE_RE.findall(r.cites):
            if not (_citation_exists(anchor, f".ai-badger/invariants/{slug}.md")
                    or _citation_exists(anchor, f"{slug}.md")):
                out.append(f"[BAD-CITES] {r.id} cites: invariant `{slug}` — "
                            f"no {slug}.md found under {anchor}")
        for token in FILE_CITE_RE.findall(r.cites):
            if not _citation_exists(anchor, token):
                out.append(f"[BAD-CITES] {r.id} cites: `{token}` — not found under {anchor}")
    return out


def check_weak_severity(rules: List[Rule]) -> List[str]:
    out = []
    for r in rules:
        if r.evidence == "weak" and (r.severity == "blocker" or r.flag == "auto"):
            out.append(f"[WEAK-SEVERITY] {r.id} is evidence: weak but "
                        f"severity: {r.severity} / flag: {r.flag}")
    return out


def check_filenames(root: Path) -> List[str]:
    refs = root / "references"
    if not refs.is_dir():
        return []
    out = []
    for path in sorted(refs.iterdir()):
        if path.is_file() and not FILENAME_RE.match(path.name):
            out.append(f"[BAD-FILENAME] references/{path.name} does not match ^[a-z][a-z-]*\\.md$")
    return out


def check_zero_rules(rules: List[Rule]) -> List[str]:
    if not rules:
        return ["[ZERO-RULES] parsed 0 rules — check the references/ directory path and file names"]
    return []


def check_duplicate_ids(rules: List[Rule]) -> List[str]:
    """Not one of the seven named classes, but a rule.json built over duplicate ids is corrupt
    (last-write-wins in every downstream lookup) — cheap to catch, so it is."""
    seen: dict = {}
    out = []
    for r in rules:
        if r.id in seen:
            out.append(f"[DUP-ID] {r.id} defined at {seen[r.id]} and again at {r.file}:{r.line}")
        else:
            seen[r.id] = f"{r.file}:{r.line}"
    return out


def run_structural_checks(root: Path, rules: List[Rule]) -> List[str]:
    out: List[str] = []
    out += check_zero_rules(rules)
    out += check_duplicate_ids(rules)
    out += check_l1_cap(rules)
    out += check_missing_parent(rules)
    out += check_dangling_parent(rules)
    out += check_absorbs_manifest(root, rules)
    out += check_cites(root, rules)
    out += check_weak_severity(rules)
    out += check_filenames(root)
    return out


# ---------------------------------------------------------------------------
# Generation — rules.json, walk-review.md, walk-design.md.
# ---------------------------------------------------------------------------

def build_index(rules: List[Rule]) -> list:
    """rules.json content: structural fields only, no prose (MoE-2-ruleset.md §3.3)."""
    out = []
    for r in sorted(rules, key=lambda r: r.id):
        out.append({
            "id": r.id,
            "layer": r.layer,
            "group": r.group,
            "title": r.title,
            "severity": r.severity,
            "evidence": r.evidence,
            "flag": r.flag,
            "parent": r.parent,
            "absorbs": r.absorbs,
            "archetypes": r.archetypes,
            "pass": r.pass_,
            "order": r.order,
            "phase": r.phase,
            "file": r.file,
            "line": r.line,
        })
    return out


def _dump_json(data) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def render_walk_review(rules: List[Rule]) -> str:
    """Passes 0-8, steps ordered by (pass, order); a rule sharing its parent's (pass, order)
    renders indented directly under it — "inserted at the parent's step number" (§5)."""
    lines = [GENERATED_BANNER, "", "# Review walk", ""]
    eligible = [r for r in rules if r.pass_ is not None and not r.is_retired]
    for p in PASSES:
        in_pass = sorted((r for r in eligible if r.pass_ == p), key=lambda r: (r.order or 0, r.id))
        if not in_pass:
            continue
        lines.append(f"## Pass {p}")
        lines.append("")
        for r in in_pass:
            prefix = "  - ↳" if r.parent else "-"
            lines.append(f"{prefix} **{r.id}** — {r.title} "
                          f"(severity: {r.severity}, flag: {r.flag})")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def render_walk_design(rules: List[Rule]) -> str:
    """Steps 1-8 from `phase:`, omitting `phase: review-only` (§6)."""
    lines = [GENERATED_BANNER, "", "# Design walk", ""]
    eligible = [r for r in rules
                if r.phase not in (None, "review-only") and not r.is_retired]
    for step in DESIGN_STEPS:
        in_step = sorted((r for r in eligible if r.phase == str(step)),
                          key=lambda r: (r.order or 0, r.id))
        if not in_step:
            continue
        lines.append(f"## Step {step}")
        lines.append("")
        for r in in_step:
            prefix = "  - ↳" if r.parent else "-"
            lines.append(f"{prefix} **{r.id}** — {r.title} "
                          f"(severity: {r.severity}, flag: {r.flag})")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def _atomic_write(path: Path, text: str) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv=None) -> int:
    """CLI entry point: build (or --check) rules.json + the two walks for a skill root."""
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", help="review-tests skill directory (default: this script's own)")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)

    default_root = Path(__file__).resolve().parent.parent
    root = Path(args.root).resolve() if args.root else default_root

    rules = parse_tree(root)
    violations = run_structural_checks(root, rules)
    if violations:
        for v in violations:
            print(v)
        print(f"{len(violations)} violation(s) — rules.json and the walks were NOT written")
        return 1

    index = build_index(rules)
    index_text = _dump_json(index)
    walk_review_text = render_walk_review(rules)
    walk_design_text = render_walk_design(rules)

    index_path = root / "rules.json"
    walk_review_path = root / "references" / "walk-review.md"
    walk_design_path = root / "references" / "walk-design.md"

    if args.check:
        drift = []
        for path, text, label in (
            (index_path, index_text, "rules.json"),
            (walk_review_path, walk_review_text, "references/walk-review.md"),
            (walk_design_path, walk_design_text, "references/walk-design.md"),
        ):
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                drift.append(f"[STALE] {label} is missing or stale — run rules_index.py")
        if drift:
            for d in drift:
                print(d)
            return 1
        print(f"rules.json and both walks up to date — {len(rules)} rules parsed")
        return 0

    _atomic_write(index_path, index_text)
    _atomic_write(walk_review_path, walk_review_text)
    _atomic_write(walk_design_path, walk_design_text)
    print(f"wrote rules.json, walk-review.md, walk-design.md — {len(rules)} rules parsed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
