#!/usr/bin/env python3
"""Emit or verify `schemas/task-plan.schema.json` against the pydantic `TaskPlan` model.

The artifact is a projection of `features/common/skills/task-decomposition/scripts/
task_plan_model.py`, loaded by path from the audited `--root` tree so the gate checks a tree's
model and artifact against each other, never the tree's artifact against another checkout's
model. The pydantic output gets exactly three injections: `$id`, `title` and a `description`
that documents the boundary (JSON Schema cannot express the DAG rules), plus
`workflow.steps.propertyNames.pattern` for the step-id grammar.

Usage: task_plan_schema.py [--root <dir>] [--check]
  (default) write schemas/task-plan.schema.json canonically
  --check   do not write; exit 1 on any difference, printing the first differing JSON pointer
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from pydantic.json_schema import GenerateJsonSchema

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "engine"))
import badger_lib as bl

MODEL_RELPATH = "features/common/skills/task-decomposition/scripts/task_plan_model.py"
SCHEMA_RELPATH = "schemas/task-plan.schema.json"
DIALECT = GenerateJsonSchema.schema_dialect
SCHEMA_ID = "https://github.com/Arasz/ai-badger/schemas/task-plan.schema.json"
SCHEMA_TITLE = "TaskPlan"
SCHEMA_DESCRIPTION = (
    "The persisted task-plan document for the task-graph MCP server. Generated by "
    "tooling/task_plan_schema.py from the pydantic model in "
    f"{MODEL_RELPATH}. JSON Schema cannot express the dependency graph: a workflow.steps key "
    "equalling its step's id, every depends_on naming a step in the same workflow, and "
    "acyclicity (a cycle in depends_on) are pydantic-only invariants enforced on every load, "
    "not by this artifact. Timestamp UTC-ness and completion consistency are likewise "
    "runtime-enforced."
)


def load_model(root: Path):
    """Import the `TaskPlan` model from `root` by path (never from an installed package)."""
    path = root / MODEL_RELPATH
    spec = importlib.util.spec_from_file_location("aib_task_plan_model", path)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load the TaskPlan model from {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _resolve_ref(schema: Dict[str, Any], node: Dict[str, Any]) -> Dict[str, Any]:
    """Follow a local `$ref` to its `$defs` target, or return `node` unchanged."""
    ref = node.get("$ref")
    if not isinstance(ref, str) or not ref.startswith("#/$defs/"):
        return node
    return schema["$defs"][ref[len("#/$defs/"):]]


def steps_schema(schema: Dict[str, Any]) -> Dict[str, Any]:
    """The `workflow.steps` object schema, following the pydantic `$ref` to `Workflow`."""
    workflow = _resolve_ref(schema, schema["properties"]["workflow"])
    return workflow["properties"]["steps"]


def build_schema(model: Any) -> Dict[str, Any]:
    """The canonical schema object: pydantic's validation schema plus artifact injections."""
    schema = model.TaskPlan.model_json_schema(mode="validation")
    schema["$schema"] = DIALECT
    schema["$id"] = SCHEMA_ID
    schema["title"] = SCHEMA_TITLE
    schema["description"] = SCHEMA_DESCRIPTION
    steps_schema(schema)["propertyNames"] = {"pattern": model.STEP_ID_PATTERN}
    return schema


def canonical_text(schema: Dict[str, Any]) -> str:
    """The on-disk form: indent 2, literal unicode, model key order, trailing newline."""
    return json.dumps(schema, indent=2, ensure_ascii=False, sort_keys=False) + "\n"


def _pointer(parts: List[str]) -> str:
    """RFC 6901 JSON pointer for the path taken so far, escaping `~` and `/`."""
    if not parts:
        return "/"
    return "/" + "/".join(part.replace("~", "~0").replace("/", "~1") for part in parts)


def first_difference(checked_in: Any, generated: Any,
                     parts: Optional[List[str]] = None) -> Optional[Tuple[str, Any, Any]]:
    """The first JSON pointer where two parsed documents differ, with both values."""
    parts = list(parts or [])
    if type(checked_in) is not type(generated):
        return _pointer(parts), checked_in, generated
    if isinstance(checked_in, dict):
        for key in sorted(set(checked_in) | set(generated)):
            if key not in checked_in or key not in generated:
                return _pointer(parts + [key]), checked_in.get(key), generated.get(key)
            found = first_difference(checked_in[key], generated[key], parts + [key])
            if found:
                return found
        return None
    if isinstance(checked_in, list):
        if len(checked_in) != len(generated):
            index = min(len(checked_in), len(generated))
            return (_pointer(parts + [str(index)]), checked_in[index:index + 1],
                    generated[index:index + 1])
        for index, (left, right) in enumerate(zip(checked_in, generated)):
            found = first_difference(left, right, parts + [str(index)])
            if found:
                return found
        return None
    if checked_in != generated:
        return _pointer(parts), checked_in, generated
    return None


def main(argv=None) -> int:
    """CLI entry point: write the artifact, or `--check` it against the model."""
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="do not write; exit 1 when the checked-in artifact differs")
    parser.add_argument("--root", help="Framework root (default: auto-detect).")
    args = parser.parse_args(argv)

    root = Path(args.root).resolve() if args.root else bl.find_root()
    generated = build_schema(load_model(root))
    path = root / SCHEMA_RELPATH

    if not args.check:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(canonical_text(generated), encoding="utf-8")
        print(f"wrote {SCHEMA_RELPATH}")
        return 0

    if not path.is_file():
        print(f"STALE {SCHEMA_RELPATH}: missing; run tooling/task_plan_schema.py")
        return 1
    checked_in = json.loads(path.read_text(encoding="utf-8"))
    difference = first_difference(checked_in, generated)
    if difference is not None:
        pointer, got, want = difference
        print(f"STALE {SCHEMA_RELPATH}: first difference at {pointer}")
        print(f"  checked in: {json.dumps(got, ensure_ascii=False)}")
        print(f"  generated:  {json.dumps(want, ensure_ascii=False)}")
        print("run tooling/task_plan_schema.py to regenerate")
        return 1
    print(f"ok {SCHEMA_RELPATH} matches the TaskPlan model")
    return 0


if __name__ == "__main__":
    sys.exit(main())
