#!/usr/bin/env python3
"""Validate an ai-badger JSON model against its schema.

Usage:
  validate.py <instance.json> [--schema <schema.json>]
  validate.py --kind {config|manifest|index|skills-source|skills|plugins-instructions|adjustment|hooks-manifest|learned-skills} <instance.json>
  validate.py --all         # validate index.json + all feature data + self-check schemas

Exit code 0 == valid, 1 == invalid, 2 == usage error. Mechanical; no LLM, no network.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "engine"))
# skills_lint is a repo gate, not a schema check; --all still reports it (the review's D4).
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "gates"))
import badger_lib as bl
from skills_lint import skills_lint

KIND_TO_SCHEMA = {
    "config": "config.schema.json",
    "manifest": "manifest.schema.json",
    "index": "index.schema.json",
    "skills-source": "skills-source.schema.json",
    "skills": "skills.schema.json",
    "plugins-instructions": "plugins-instructions.schema.json",
    "adjustment": "adjustment.schema.json",
    "hooks-manifest": "hooks-manifest.schema.json",
    "learned-skills": "learned-skills.schema.json",
}

# Every catalog file --all validates, as root-relative globs per schema. Adding a schema
# without a line here fails test_every_schema_has_a_coverage_decision.
SCHEMA_INSTANCES = {
    "index.schema.json": ["index.json"],
    "skills-source.schema.json": ["features/*/skills-source.json"],
    "skills.schema.json": ["features/*/skills.json"],
    "hooks-manifest.schema.json": ["features/*/hooks/hooks-manifest.json"],
    "adjustment.schema.json": ["features/*/adjustments/adjustment.json"],
    "plugins-instructions.schema.json": ["features/*/plugins-instructions.json"],
    "stack-mcp.schema.json": ["features/*/stack-mcp.json"],
    "mcp-server.schema.json": ["features/*/mcp/*/meta.json"],
    "mcp-server-tools.schema.json": ["features/*/mcp/*/tools.json"],
    "stack.schema.json": ["features/*/stack.json"],
    "dependencies.schema.json": ["features/*/dependencies.json"],
    "scaffolding.schema.json": ["features/*/scaffolding.json"],
    "support.schema.json": ["features/*/support.json"],
    "model.schema.json": ["features/*/templates/agent-instructions/model.template.json"],
    "hooks.schema.json": ["features/*/hooks/hooks.json"],
    "mcp-tags.schema.json": ["features/*/mcp-tags.json"],
    "skill-extension.schema.json": ["features/*/skills/*/extensions/*/extension.json",
                                    "features/*/skills/*/references/*/extensions/*/extension.json"],
}

# JSON under features/ that no schema validates, and why. A file matching neither a
# SCHEMA_INSTANCES glob nor one of these is a violation: SCHEMA_INSTANCES only proves a
# schema has instances, never that an instance has a schema (the review's A16).
FEATURE_JSON_WITHOUT_SCHEMA: Dict[str, str] = {
    "features/*/skills/*/manifest.json":
        "gateway manifest (ADR-0021); its structure — kind, members, paths, purpose "
        "byte-equality, orphans — is validated by skills_lint rule 13, and a JSON Schema here "
        "would be a second copy of that shape",
    "features/*/tsconfig.json":
        "TypeScript compiler configuration for a feature's own type-check gate; its shape is "
        "the TypeScript vendor's contract and tsc itself is the validator that reads it",
    "features/pi/package.json":
        "the bun/tsc gate harness manifest for features/pi — a workspace manifest pinning "
        "typescript and the pi package so the TS lane's gates can run; it configures a "
        "toolchain, not a feature, and ai-badger's schema machinery never reads it",
    "features/*/adjustments/adapter/package.json":
        "pi hooks adapter package.json — a pi extension manifest like the cron one below; "
        "pi discovers the extension by its index.ts, so this file is npm's contract, not ours",
    "features/*/cron/package.json":
        "pi cron extension package.json — a pi extension manifest, not a feature-config "
        "JSON; validates against npm's package.json schema and is never read by ai-badger's "
        "own schema machinery",
    "features/*/skills/review-tests/rules.json":
        "generated by the skill's own scripts/rules_index.py from the references/*.md rule "
        "records and verified stale-or-not by its --check; the markdown is the truth, so a "
        "schema here would be a second copy of the generator's output shape",
    "features/*/skills/*/hooks/settings-snippet.json":
        "a verbatim fragment of the agent's own settings.json, merged in as-is; its shape is "
        "the agent vendor's contract, not ours, so a schema here would only go stale",
    "features/*/skills/*/markers-context.json":
        "free-form prompt context the prompt-markers skill injects; the keys are prose slots "
        "the skill reads by name, with no cross-file contract to hold them to",
    "features/*/skills/*/evals/*.json":
        "retrieval eval fixtures (ADR-0012), consumed only by the eval harness that ships "
        "beside them; wired into no lane today, so a schema would outlive its only reader",
    "features/common/retrieval/eval/*.json":
        "pinned baseline MCP index used by retrieval evaluation suites to ensure evaluation "
        "reproducibility across consumer repo index sizes",
    "features/*/templates/agent-instructions/schema.json":
        "shipped output, not input: this is the JSON Schema a scaffolded project gets for its "
        "own agent-instructions model, and it is self-validating as a schema",
    "features/*/templates/state.json":
        "the seed body of a scaffolded project's .ai-badger/state.json; owned by the tracker "
        "that reads it in the consumer project, and it carries no framework-side contract",
    "features/*/skills/*/templates/*.json":
        "a seed body the skill tells its reader to copy out and fill in, not framework input: "
        "the filled copy lives in the consumer project and the blank one is only ever read by "
        "the human following the skill. Its shape is pinned by that skill's own tests, which "
        "assert what a schema cannot — that a field stays unanswerable-by-default",
}

# Stacks whose files are not checked for cross-stack references, and why.
CROSS_STACK_REFERENCE_EXEMPT: Dict[str, str] = {
    "common":
        "common ships in every scaffold and has no `requires` closure of its own to violate: "
        "its mentions of stack artifacts are illustrative examples inside prose, not "
        "instructions to go read a file. Checking it would mean hedging a dozen sentences "
        "rather than fixing a dangling pointer. The residual risk is real but bounded — a "
        "common skill naming a dotnet skill still reads oddly in a python-only project.",
}

# Feature directories carrying per-item artifacts a sibling stack's file may point at.
REFERENCEABLE_FEATURES = ("personas", "invariants", "instructions", "skills")

# Globs for the bodies copied into the generated agent files, so a link inside them is read from
# the consumer's repo root rather than from where the file lives. MCP server bodies fill the
# MCP_INSTRUCTIONS slot and sit one directory deeper than the rest.
INLINED_BODY_GLOBS = ("*/invariants/*.md", "*/instructions/*.md", "*/mcp/*/*.md")

# Schemas with no instance in this repo, and why. Listed so the completeness check stays
# honest rather than silently shrinking.
SCHEMAS_WITHOUT_LOCAL_INSTANCES = {
    "config.schema.json": "instances live in consumer projects (.ai-badger/config.json)",
    "manifest.schema.json": "instances live in consumer projects (.ai-badger/manifest.json)",
    "learned-skills.schema.json": "instances live in consumer projects (skills-data/)",
    "agents.schema.json": "vocabulary schema, referenced by others; no standalone instance",
    "mcp-tools.schema.json": "instances live in consumer projects (.ai-badger/mcp-tools.json)",
}

# Agents capable of every hook event family this framework wires: SessionStart/on_session_start/
# sessionStart, UserPromptSubmit/pre_llm_call/userPromptSubmitted, PostToolUse-PreToolUse/
# post_tool_call-pre_tool_call/postToolUse-preToolUse, and Stop-SessionEnd/on_session_end/
# agentStop-sessionEnd (docs/dictionary.md "Hooks"). A hooks-
# manifest.json entry missing one of these must say why (see HOOKS_MANIFEST_AGENT_EXEMPTIONS)
# instead of silently never reaching it — issue #147 was the third occurrence of exactly that.
HOOK_CAPABLE_AGENTS = ("claude", "hermes", "copilot")

# hook name -> {agent: reason} for a hook that deliberately does not reach one of
# HOOK_CAPABLE_AGENTS. Every reason is asserted non-trivial by
# tests/test_hooks_manifest_agent_coverage.py (the #145 review finding: an untested reason
# string is not a reason, only a key that happens to exist).
HOOKS_MANIFEST_AGENT_EXEMPTIONS: Dict[str, Dict[str, str]] = {
    "session-start-tracking": {
        "hermes": "Claude-only by design: recording the session id/transcript path, surfacing "
                  "unfinished tracked tasks, and starting the usage-limit poller are all Claude "
                  "Code concepts (transcript files, Claude's own usage limits) with no Hermes "
                  "analogue to wire onto.",
        "copilot": "Claude-only by design, same reasoning as the hermes exemption above: "
                   "nothing here maps onto a Copilot concept either.",
    },
    "task-checkpoint": {
        "hermes": "Claude-only for the same reason session-start-tracking is: the tracked-task "
                  "record this hook refreshes only ever exists because session-start-tracking "
                  "wrote a Claude session id onto it, and the numbers come from parsing that "
                  "session's Claude transcript JSONL, which Hermes does not produce. Wired onto "
                  "on_session_end it would match no task and measure nothing.",
        "copilot": "Claude-only, same reasoning as the hermes exemption above, plus a second "
                   "wall: Copilot has an agentStop event but keeps its usage in "
                   "~/.copilot/session-store.db rather than a transcript JSONL, and its hook "
                   "protocol has no block-with-reason channel for the enforcement half to use.",
    },
    "task-checkpoint-session-end": {
        "hermes": "Inherits the task-checkpoint exemption verbatim — same script, same "
                  "Claude-only tracked-task ledger and transcript JSONL, only a different "
                  "event. Hermes' on_session_end carries completed/interrupted booleans and "
                  "neither a session id nor a transcript path to checkpoint from.",
        "copilot": "Inherits the task-checkpoint exemption verbatim — same script, same "
                   "Claude-only tracked-task ledger and transcript JSONL. Copilot's sessionEnd "
                   "would fire correctly and find nothing to write.",
    },
    "dispatch-gate": {
        "hermes": "Nothing per-dispatch to gate, verified against Hermes 0.20.6's own schema "
                  "rather than inferred: DELEGATE_TASK_SCHEMA's per-task properties are exactly "
                  "goal, context and output_schema (tools/delegate_tool.py), so a delegate_task "
                  "call carries neither a model nor an isolation argument a pre_tool_call hook "
                  "could find missing. Hermes does isolate subagents, but by config — "
                  "delegation.worktree_isolation, default false — which is a session-wide "
                  "setting, not a dispatch argument; ai_badger_hooks warns on session start when "
                  "it is off. Why the previous reason here was wrong: "
                  "docs/changelog/0.140.0-hermes-cannot-be-gated-per-dispatch.md.",
        "copilot": "Acknowledged gap on the model-lane half, a wall on the enforcement half: "
                   "Copilot does fire preToolUse and does keep a model in .github/agents/"
                   "*.agent.md frontmatter, so reading the lane is possible and simply has not "
                   "been done — but its hook protocol has no block-with-reason channel, and a "
                   "deny with the fix in it is this hook's entire output.",
    },
    "prompt-markers": {
        "hermes": "Acknowledged gap, not a design limit: marker detection (h:/f:/e:) has no "
                  "Hermes-side implementation yet, unlike session-start-tracking's Claude-only "
                  "design — wiring it on Hermes is possible and simply "
                  "has not been done.",
    },
    "generated-file-guard": {
        "hermes": "Acknowledged gap, not a design limit: Hermes fires pre_tool_call and can "
                  "refuse, so the guard would work there — the scaffold manifest it reads is "
                  "agent-independent. It has not been done, and shipping the arm without a "
                  "session that exercised it is the failure this hook's own review names.",
        "copilot": "A wall, not a gap: Copilot fires preToolUse but its hook protocol has no "
                   "block-with-reason channel, and a refusal naming the features/ file to edit "
                   "instead is this guard's entire output. A silent block would teach nothing.",
    },
    "blast-radius-kill-guard": {
        "hermes": "A wall on the input, not the output: the guard denies only while two or more "
                  "agent lanes are plausibly live, and it counts them from the per-process "
                  "socket directory Claude Code keeps for its own sessions. Hermes publishes no "
                  "equivalent registry of live lanes, so an arm there would classify the hazard "
                  "correctly and then always find zero lanes and allow — a gate that can only "
                  "ever say yes.",
        "copilot": "A wall on both halves: Copilot fires preToolUse but its hook protocol has "
                   "no block-with-reason channel, and a denial naming the scoped kill to use "
                   "instead is this guard's entire output — plus it would still need a live-lane "
                   "count Copilot does not expose.",
    },
    "cross-worktree-dirty-warning": {
        "hermes": "Acknowledged gap, not a design limit: the sweep is pure git (worktree list "
                  "plus per-tree status) and agent-independent, so it would work on "
                  "pre_tool_call — it has not been done, and no Hermes-side channel for a "
                  "non-blocking note back to the model has been chosen yet.",
        "copilot": "Acknowledged gap on the same terms: Copilot fires preToolUse over the "
                   "edit-shaped tools and the git sweep needs nothing Claude-specific, but this "
                   "hook only ever warns and Copilot's hook protocol has no channel that puts a "
                   "non-blocking note in front of the model.",
    },
    "git-internals-guard": {
        "copilot": "A wall, not a gap: Copilot fires preToolUse but its hook protocol has no "
                   "block-with-reason channel, and a refusal naming `git config`/`git remote` as "
                   "the transactional route is this guard's entire output. A silent block would "
                   "leave the agent retrying the same hand edit with no idea why it vanished.",
    },
    "git-config-health": {
        "hermes": "Acknowledged gap, not a design limit: the check is pure git (`git config "
                  "--get` against the common dir) and agent-independent, so it would work on "
                  "on_session_start — the Hermes dispatcher already carries drift-notice there "
                  "and a second notice needs a channel decision that has not been made.",
    },
}

PROVENANCE_KEYS = ("frameworkCommit", "frameworkDirty")

PROVENANCE_HINT = (
    "This manifest predates ai-badger 0.2.0, which requires provenance keys "
    "(frameworkCommit, frameworkDirty). There is no migration by design — "
    "re-scaffold with welcome-ai-badger to upgrade it. Seed-once files "
    "(state.json, markers-context.json, agent-instructions/model.json) are preserved "
    "across a re-scaffold; "
    "review the diff before committing. See docs/adr/0001-versioning-and-release-model.md."
)


def provenance_hint(errors: List[str]) -> Optional[str]:
    """Return an actionable upgrade hint when errors are missing-provenance-key errors."""
    if any(key in err and "is a required property" in err
           for err in errors for key in PROVENANCE_KEYS):
        return PROVENANCE_HINT
    return None


def _report(label: str, errors) -> bool:
    if errors:
        print(f"INVALID  {label}")
        for e in errors:
            print(f"    - {e}")
        hint = provenance_hint(errors)
        if hint:
            print(f"    → {hint}")
        return False
    print(f"ok       {label}")
    return True


def undecided_schemas(root: Path) -> List[str]:
    """Schemas in schemas/ that SCHEMA_INSTANCES and the exemption list both ignore."""
    shipped = {p.name for p in (root / "schemas").glob("*.schema.json")}
    decided = set(SCHEMA_INSTANCES) | set(SCHEMAS_WITHOUT_LOCAL_INSTANCES)
    return sorted(shipped - decided)


HOOKS_MANIFEST_GLOB = "features/*/hooks/hooks-manifest.json"


def hooks_manifest_agent_gaps(root: Path) -> List[str]:
    """Every (hook, agent) pair reaching neither a manifest entry nor a recorded exemption.

    Walks every `hooks-manifest.json` this framework ships (currently exactly one,
    features/common/hooks/hooks-manifest.json) and checks each hook's `agents` map against
    HOOK_CAPABLE_AGENTS. A hook naming an agent is covered; a hook naming neither the agent nor
    an exemption in HOOKS_MANIFEST_AGENT_EXEMPTIONS is a gap — the shape issue #147 was the third
    occurrence of. A glob matching no manifest at all is itself a gap: checking nothing and
    finding nothing are not the same answer.
    """
    manifests = sorted(root.glob(HOOKS_MANIFEST_GLOB))
    if not manifests:
        return [f"{HOOKS_MANIFEST_GLOB} matched no file: this check ran against no input"]
    gaps: List[str] = []
    for manifest_path in manifests:
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        rel = manifest_path.relative_to(root)
        for hook in manifest.get("hooks", []):
            name = hook.get("name", "<unnamed>")
            agents = hook.get("agents", {})
            exemptions = HOOKS_MANIFEST_AGENT_EXEMPTIONS.get(name, {})
            for agent in HOOK_CAPABLE_AGENTS:
                if agent in agents or agent in exemptions:
                    continue
                gaps.append(
                    f"{rel}: hook '{name}' has no '{agent}' entry and no recorded exemption in "
                    f"HOOKS_MANIFEST_AGENT_EXEMPTIONS"
                )
    return gaps


def catalog_stacks(root: Path) -> List[str]:
    """Stack names the catalog can actually deliver: a stack.json, a feature directory, or both.

    Mirrors index_build.build_index's own membership rule, so this set is exactly
    index.json.stacks without needing a built index to compare against.
    """
    names = {stack for stack, _, _ in bl.iter_feature_dirs(root)}
    features_root = root / "features"
    if features_root.is_dir():
        names |= {d.name for d in features_root.iterdir()
                  if d.is_dir() and (d / "stack.json").is_file()}
    return sorted(names)


def candidate_stack_dirs(root: Path) -> List[str]:
    """Directory names directly under features/, read from HEAD wherever git can answer.

    An untracked directory is not a stack the catalog ships, so it is not a gap either — a
    validator reading the working tree failed on whatever the session had left behind. A root
    with no index (a fixture, an unpacked tarball) has only its working tree to go on. The
    leading-dot rule applies to both: local state lands in `features/.ai-badger/`, and being
    committed does not make it a stack.
    """
    tracked = bl.run_git(["ls-tree", "-d", "--name-only", "HEAD", "features/"], root)
    if tracked.returncode == 0:
        names = (line.rsplit("/", 1)[-1] for line in tracked.stdout.splitlines() if line)
    else:
        names = (d.name for d in (root / "features").iterdir() if d.is_dir())
    return sorted(name for name in names if not name.startswith("."))


def catalog_stack_gaps(root: Path) -> List[str]:
    """features/<dir> that delivers nothing — the shape features/github had (the review's C14)."""
    if not (root / "features").is_dir():
        return []
    known = set(catalog_stacks(root))
    return [f"features/{name}: no stack.json and no feature directory, so the index never "
            f"sees it — populate it or delete it"
            for name in candidate_stack_dirs(root) if name not in known]


def config_stack_gaps(root: Path, config: Dict) -> List[str]:
    """Stacks a config selects that the catalog cannot deliver.

    `agents` names catalog directories as much as `stacks` does (badger_lib.delivering_stacks),
    so both are checked. config.schema.json states this rule only in a description string.
    """
    known = set(catalog_stacks(root))
    if not known:
        return []
    common = config.get("commonStacks", "common")
    selected = {
        "stacks": config.get("stacks") or [],
        "agents": config.get("agents") or [],
        "commonStacks": [common] if isinstance(common, str) else list(common or []),
    }
    return [f"config.{key} names {name!r}, which the catalog does not ship "
            f"(known: {', '.join(sorted(known))})"
            for key, names in selected.items() for name in names if name not in known]


def _is_vendored(path: Path) -> bool:
    """A dependency directory is a build artifact, not catalog the framework ships."""
    return "node_modules" in path.parts


def unschemad_feature_json(root: Path) -> List[str]:
    """JSON under features/ that no schema validates and no exemption names (the review's A16)."""
    features_root = root / "features"
    if not features_root.is_dir():
        return []
    covered = {p for patterns in SCHEMA_INSTANCES.values()
               for pattern in patterns for p in root.glob(pattern)}
    covered |= {p for pattern in FEATURE_JSON_WITHOUT_SCHEMA for p in root.glob(pattern)}
    return [f"{p.relative_to(root).as_posix()}: matched by no schema — add a SCHEMA_INSTANCES "
            f"glob or an entry in FEATURE_JSON_WITHOUT_SCHEMA with a reason"
            for p in sorted(features_root.rglob("*.json"))
            if p not in covered and not _is_vendored(p)]


def _stack_requires(root: Path, stack: str) -> List[str]:
    sj = root / "features" / stack / "stack.json"
    return list(bl.load_json(sj).get("requires", [])) if sj.is_file() else []


def _requires_closure(root: Path, stack: str) -> set:
    out = {stack, "common"}
    pending = [stack]
    while pending:
        for req in _stack_requires(root, pending.pop()):
            if req not in out:
                out.add(req)
                pending.append(req)
    return out


def _artifact_owners(root: Path) -> Dict[str, set]:
    """Artifact name -> the stacks that ship it, over the referenceable feature types.

    Hyphenated names only: a bare one-word name (`mcp`, `css`, `task`) is ordinary prose
    wherever it appears, so matching it would report noise instead of dangling pointers.
    """
    owners: Dict[str, set] = {}
    for stack, feature, fdir in bl.iter_feature_dirs(root):
        if feature not in REFERENCEABLE_FEATURES:
            continue
        for item in sorted(fdir.iterdir()):
            name = item.name if item.is_dir() else item.stem
            if (item.is_dir() or item.suffix == ".md") and "-" in name:
                owners.setdefault(name, set()).add(stack)
    return owners


def inlined_relative_links(root: Path) -> List[str]:
    """A relative markdown link in a body that gets inlined somewhere else (0.112.0's defect).

    `cross-stack references` resolves a link where the file *lives*, which is why the broken one
    passed. These bodies are copied into the generated agent files at the consumer's repo root,
    a different depth in a different tree, so a path correct here points outside the repo there.
    An absolute URL survives the move; nothing else does.
    """
    gaps: List[str] = []
    for glob in INLINED_BODY_GLOBS:
        for path in sorted((root / "features").glob(glob)):
            if path.name == "README.md":
                continue
            for target in re.findall(r"\]\(([^)]+)\)", path.read_text(encoding="utf-8")):
                if "://" in target or target.startswith("#"):
                    continue
                gaps.append(
                    f"{path.relative_to(root).as_posix()}: relative link {target!r} — this body "
                    "is inlined into the agent files, where the path does not resolve. Use an "
                    "absolute URL or name the target in prose.")
    return gaps


def cross_stack_reference_gaps(root: Path) -> List[str]:
    """A stack's file naming an artifact only another, undeclared stack ships (the review's C8).

    `features/dotnet` declares `requires: []`, so a dotnet-only scaffold has no
    `cloud-infra-engineer` — yet its persona sent readers to one.
    """
    owners = _artifact_owners(root)
    gaps: List[str] = []
    for stack_dir in sorted(p for p in (root / "features").glob("*") if p.is_dir()):
        stack = stack_dir.name
        if stack in CROSS_STACK_REFERENCE_EXEMPT:
            continue
        closure = _requires_closure(root, stack)
        candidates = [(n, o) for n, o in owners.items() if not o & closure]
        for path in sorted(stack_dir.rglob("*.md")):
            text = path.read_text(encoding="utf-8", errors="replace")
            gaps += [
                f"{path.relative_to(root).as_posix()}: names {name!r}, shipped only by "
                f"{'/'.join(sorted(own))}, which {stack} does not require"
                for name, own in candidates
                if re.search(r"(?<![\w-])" + re.escape(name) + r"(?![\w-])", text)]
    return sorted(gaps)


def validate_all(root: Path) -> int:
    """Validate every catalog file SCHEMA_INSTANCES maps, plus the schemas themselves."""
    ok = True
    ok &= _report("schemas self-check", bl.check_schemas_selfvalid(root / "schemas"))

    ok &= _report("schema coverage",
                  [f"{name} validates nothing: add it to SCHEMA_INSTANCES or to "
                   f"SCHEMAS_WITHOUT_LOCAL_INSTANCES with a reason"
                   for name in undecided_schemas(root)])

    for schema_name, patterns in sorted(SCHEMA_INSTANCES.items()):
        schema_path = root / "schemas" / schema_name
        if not schema_path.is_file():
            ok &= _report(f"schemas/{schema_name}", ["declared in SCHEMA_INSTANCES but missing"])
            continue
        for pattern in patterns:
            for instance in sorted(root.glob(pattern)):
                ok &= _report(str(instance.relative_to(root)),
                              bl.validate_file(instance, schema_path))

    ok &= _report("catalog stack membership", catalog_stack_gaps(root))
    ok &= _report("feature json schema coverage", unschemad_feature_json(root))
    ok &= _report("cross-stack references", cross_stack_reference_gaps(root))
    ok &= _report("inlined bodies carry no relative links", inlined_relative_links(root))
    ok &= _report("hooks-manifest agent coverage", hooks_manifest_agent_gaps(root))
    ok &= _report("skills lint", skills_lint(root))
    return 0 if ok else 1


def main(argv=None) -> int:
    """CLI entry point: validate one instance (--schema/--kind) or the whole tree (--all)."""
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("instance", nargs="?", help="Path to the JSON instance to validate.")
    ap.add_argument("--schema", help="Explicit schema path.")
    ap.add_argument("--kind", choices=sorted(KIND_TO_SCHEMA))
    ap.add_argument("--all", action="store_true", help="Validate the whole framework tree.")
    ap.add_argument("--root", help="Framework root (default: auto-detect).")
    args = ap.parse_args(argv)

    root = Path(args.root).resolve() if args.root else bl.find_root()

    if args.all:
        return validate_all(root)

    if not args.instance:
        ap.error("provide an instance path or --all")
    inst = Path(args.instance).resolve()

    schema_path = None
    if args.schema:
        schema_path = Path(args.schema).resolve()
    elif args.kind:
        schema_path = root / "schemas" / KIND_TO_SCHEMA[args.kind]
    else:
        ap.error("provide --schema or --kind")

    ok = _report(str(inst), bl.validate_file(inst, schema_path))
    if ok and schema_path.name == KIND_TO_SCHEMA["config"]:
        # The schema states stack membership only in a description string; a config selecting a
        # stack the catalog cannot deliver is otherwise valid (the review's C14).
        ok &= _report("config stack membership", config_stack_gaps(root, bl.load_json(inst)))
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())